version: '3'

services:
  glassy-pass:
    image: nginx:alpine
    container_name: glassy-pass
    restart: unless-stopped
    ports:
      - "8899:80"
    volumes:
      - ./:/usr/share/nginx/html:ro